import Head from 'next/head';
import CardArticle from '../components/card-article';

export default function Home() {
  return (
    <>
      <Head>
        <title>Simple Card Slider</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="pt-10">
        <h2 className="mb-6 pl-10 text-2xl font-bold">Latest Posts</h2>
        <div className="scroll-hidden flex snap-x snap-mandatory gap-5 overflow-x-auto px-10 antialiased lg:gap-10">
          <CardArticle
            image="https://images.unsplash.com/photo-1539584222411-a76a40e9e861?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
            category="social media"
            title="3 things i learned after meditating for 100 weeks straight"
          />

          <CardArticle
            image="https://images.unsplash.com/photo-1671212527047-92e48e4bda60?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
            category="technology"
            title="The best password managers for all your online accounts"
          />

          <CardArticle
            image="https://images.unsplash.com/photo-1670775083217-64b6b1b8d00e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
            category="business"
            title="The Best Mental Health Books of 2022"
          />
          <CardArticle
            image="https://images.unsplash.com/photo-1667423520863-8653106f18e7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=928&q=80"
            category="social media"
            title="This Powerful, Churning Cyclone Is About to Hit California"
          />
        </div>
      </section>
    </>
  );
}
